### ISSUE TITLE
Tests do not pass in freshly setuped environment

### ISSUE THREAD

**Issue by strazdas** [python-dirbtuves/akl.lt#51]
I followed instructions on README.rst for Ubuntu environment and got this traceback, when ran tests:

```......FE......FF...F..............SFF..```
```======================================================================```
```ERROR: test_command (akllt.dataimport.tests.test_importzope.ImportZopeCommandTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_importzope.py", line 14, in test_command```
```    call_command('akllt_importzope', fixture('whole_export'), verbosity=0)```
```  File "/home/strazdas/.buildout/eggs/Django-1.7-py3.4.egg/django/core/management/__init__.py", line 115, in call_command```
```    return klass.execute(*args, **defaults)```
```  File "/home/strazdas/.buildout/eggs/Django-1.7-py3.4.egg/django/core/management/base.py", line 338, in execute```
```    output = self.handle(*args, **options)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/management/commands/akllt_importzope.py", line 94, in handle```
```    total = sum(1 for _ in generator)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/management/commands/akllt_importzope.py", line 94, in <genexpr>```
```    total = sum(1 for _ in generator)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/convertlinks.py", line 106, in convert_links```
```    convert_page_link(page)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/convertlinks.py", line 99, in convert_page_link```
```    page.body = A_TAG_RE.sub(replace_links, page.body)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/convertlinks.py", line 95, in replace_links```
```    return format_wagtail_tag(page, link)```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/convertlinks.py", line 80, in format_wagtail_tag```
```    ref_page = Page.objects.get(url_path=url_path)```
```  File "/home/strazdas/.buildout/eggs/Django-1.7-py3.4.egg/django/db/models/manager.py", line 92, in manager_method```
```    return getattr(self.get_queryset(), name)(*args, **kwargs)```
```  File "/home/strazdas/.buildout/eggs/Django-1.7-py3.4.egg/django/db/models/query.py", line 357, in get```
```    self.model._meta.object_name)```
```nose.proxy.DoesNotExist: Page matching query does not exist.```
```-------------------- >> begin captured stdout << ---------------------```
```Successfully imported 16 and updated 0 items. Total 16 items processed.```
``` ```
```--------------------- >> end captured stdout << ----------------------```
``` ```
```======================================================================```
```FAIL: test_get_total (akllt.dataimport.tests.test_importmanager.ImportManagerTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_importmanager.py", line 18, in test_get_total```
```    self.assertEqual(manager.get_total(), 14)```
```AssertionError: 16 != 14```
``` ```
```======================================================================```
```FAIL: test_import (akllt.dataimport.tests.test_pages_import.PagesImporterTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_pages_import.py", line 85, in test_import```
```    ('/home/ak/sekme/', 'Sėkmės istorijos'),```
```AssertionError: Lists differ: [('/h[88 chars]e/ak/atviri_standartai/atviri_standartai/', 'A[714 chars]os')] != [('/h[88 chars]e/ak/dokumentacija/', 'Dokumentacija'), ('/hom[556 chars]os')]```
``` ```
```First differing element 2:```
```('/home/ak/atviri_standartai/atviri_standartai/', 'Atviri standartai, protokolai, formatai. Kodėl Lietuvai jų reikia?')```
```('/home/ak/dokumentacija/', 'Dokumentacija')```
``` ```
```First list contains 2 additional elements.```
```First extra element 14:```
```('/home/ak/osd/', 'Atvirojo kodo apibrėžimas')```
``` ```
```Diff is 910 characters long. Set self.maxDiff to None to see it.```
``` ```
```======================================================================```
```FAIL: test_iterate_paths (akllt.dataimport.tests.test_pages_import.PagesImporterTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_pages_import.py", line 52, in test_iterate_paths```
```    'ak/sekme.html',```
```AssertionError: Lists differ: ['ak/[24 chars] 'ak/atviri_standartai/atviri_standartai.zpt',[268 chars]tml'] != ['ak/[24 chars] 'ak/dokumentacija.html', 'ak/floss.html', 'ak[205 chars]tml']```
``` ```
```First differing element 1:```
```ak/atviri_standartai/atviri_standartai.zpt```
```ak/dokumentacija.html```
``` ```
```First list contains 2 additional elements.```
```First extra element 12:```
```ak/osd.html```
``` ```
```  ['ak/atviri_standartai.html',```
```-  'ak/atviri_standartai/atviri_standartai.zpt',```
```   'ak/dokumentacija.html',```
```   'ak/floss.html',```
```   'ak/free-sw.html',```
```   'ak/knygos.html',```
```-  'ak/laisve.zpt',```
```   'ak/licencijos/apie.html',```
```   'ak/licencijos/copyleft.html',```
```   'ak/licencijos/gpl.html',```
```   'ak/licencijos/kategorijos.html',```
```   'ak/licencijos/lgpl.html',```
```   'ak/osd.html',```
```   'ak/sekme.html']```
``` ```
```======================================================================```
```FAIL: test_menu_tree (akllt.website.tests.test_navigation.ManuTreeTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/website/tests/test_navigation.py", line 75, in test_menu_tree```
```    '</ul>',```
```AssertionError: Lists differ: ['<ul[52 chars], '<a>p2</a>', '</li>', '<li class="active">',[124 chars]ul>'] != ['<ul[52 chars], '<a href="/p1/p2/">p2</a>', '</li>', '<li cl[157 chars]ul>']```
``` ```
```First differing element 2:```
```<a>p2</a>```
```<a href="/p1/p2/">p2</a>```
``` ```
```  ['<ul class="depth-1 nav nav-pills nav-stacked">',```
```   '<li>',```
```-  '<a>p2</a>',```
```+  '<a href="/p1/p2/">p2</a>',```
```   '</li>',```
```   '<li class="active">',```
```   '<a href="#">p4</a>',```
```   '<ul class="depth-2 nav nav-pills nav-stacked">',```
```   '<li>',```
```-  '<a>p5</a>',```
```+  '<a href="/p1/p4/p5/">p5</a>',```
```   '</li>',```
```   '</ul>',```
```   '</li>',```
```   '</ul>']```
``` ```
```======================================================================```
```FAIL: test_image_fixture (akllt.dataimport.tests.test_iter_paths.IterPathsTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_iter_paths.py", line 20, in test_image_fixture```
```    'naujiena_0944', 'naujiena_1020', 'naujiena_0007', 'naujiena_0985',```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_iter_paths.py", line 15, in assert_paths```
```    self.assertEqual(paths, expected)```
```AssertionError: Lists differ: ['naujiena_0007', 'naujiena_0944', 'naujiena_1020', 'naujiena_0985'] != ['naujiena_0944', 'naujiena_1020', 'naujiena_0007', 'naujiena_0985']```
``` ```
```First differing element 0:```
```naujiena_0007```
```naujiena_0944```
``` ```
```- ['naujiena_0007', 'naujiena_0944', 'naujiena_1020', 'naujiena_0985']```
```+ ['naujiena_0944', 'naujiena_1020', 'naujiena_0007', 'naujiena_0985']```
``` ```
```======================================================================```
```FAIL: test_whole_export (akllt.dataimport.tests.test_iter_paths.IterPathsTests)```
```----------------------------------------------------------------------```
```Traceback (most recent call last):```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_iter_paths.py", line 44, in test_whole_export```
```    'licencijos/kategorijos.html',```
```  File "/home/strazdas/Desktop/akl_tmp/akl.lt/akllt/dataimport/tests/test_iter_paths.py", line 15, in assert_paths```
```    self.assertEqual(paths, expected)```
```AssertionError: Lists differ: ['floss.html', 'atviri_standartai.html', '1[305 chars]zpt'] != ['atviri_standartai.html', 'knygos.html', '[305 chars]tml']```
``` ```
```First differing element 0:```
```floss.html```
```atviri_standartai.html```
``` ```
```Diff is 779 characters long. Set self.maxDiff to None to see it.```
``` ```
```Name                                                    Stmts   Miss  Cover   Missing```
```-------------------------------------------------------------------------------------```
```akllt                                                       0      0   100%   ```
```akllt.common                                                0      0   100%   ```
```akllt.common.htmlutils                                     65      6    91%   36, 106, 109-110, 113-114```
```akllt.common.treeutils                                     32      0   100%   ```
```akllt.dataimport                                            0      0   100%   ```
```akllt.dataimport.convertlinks                              52      4    92%   48-49, 56, 75```
```akllt.dataimport.exceptions                                 2      0   100%   ```
```akllt.dataimport.importers                                  0      0   100%   ```
```akllt.dataimport.importers.base                           170     11    94%   138, 143, 175, 192, 305-308, 311-314```
```akllt.dataimport.importers.news                            14      0   100%   ```
```akllt.dataimport.importers.pages                           41      0   100%   ```
```akllt.dataimport.importmanager                             20      0   100%   ```
```akllt.dataimport.management                                 0      0   100%   ```
```akllt.dataimport.management.commands                        0      0   100%   ```
```akllt.dataimport.management.commands.akllt_importzope      50     10    80%   35, 56, 65, 68-72, 77, 89-90, 96```
```akllt.dataimport.wagtail                                    8      2    75%   10-11```
```akllt.dataimport.z2loader                                  48      3    94%   30, 36, 45```
```akllt.homepage                                              0      0   100%   ```
```akllt.homepage.models                                       7      7     0%   1-10```
```akllt.log                                                  14      9    36%   1-5, 10-15```
```akllt.news                                                  0      0   100%   ```
```akllt.news.feeds                                           13     13     0%   1-20```
```akllt.news.models                                          30     30     0%   1-68```
```akllt.news.urls                                             3      3     0%   1-6```
```akllt.pages                                                 0      0   100%   ```
```akllt.pages.models                                         13     13     0%   3-28```
```akllt.settings                                              0      0   100%   ```
```akllt.settings.base                                        38     38     0%   11-266```
```akllt.settings.development                                  1      1     0%   3```
```akllt.stub                                                  0      0   100%   ```
```akllt.stub.urls                                             2      2     0%   1-4```
```akllt.stub.views                                           15     15     0%   1-29```
```akllt.website                                               0      0   100%   ```
```akllt.website.helpers                                       0      0   100%   ```
```akllt.website.middleware                                   13      5    62% 1-5, 22, 27```
```akllt.website.navigation                                    4      0   100%  ```
```akllt.website.templatetags                                  0      0   100%  ``` 
```akllt.website.templatetags.navtags                         45     13    71%   16-26, 66, 71-77```
```-------------------------------------------------------------------------------------```
```TOTAL                                                     700    185    74%```   
```----------------------------------------------------------------------```
```Ran 39 tests in 1.133s```
``` ```
```FAILED (SKIP=1, errors=1, failures=6)```
```make: *** [test] Error 1```

**Comment by strazdas** [comment]
Mantas fixed this with e984871
